// SSOT for Pencil token parity tests and future theme audits — do not delete.
export const PENCIL_TOKENS = Object.freeze({
  light: Object.freeze({
    bg: "#f8f4ed",
    surface: "#fefbf6",
    "surface-inset": "#f1ebe0",
    border: "#e6dfd3",
    "text-primary": "#1a1614",
    "text-secondary": "#5a5550",
    "text-muted": "#8a847c",
    "on-primary": "#f8f4ed",
    "brand-mint": "#0a8268",
    "brand-green": "#0c8a5e",
    "brand-blue": "#1158b0",
    "brand-violet": "#6b3fa8",
    primary: "#0c8a5e",
    coral: "#c70067",
    "warm-yellow": "#ff9728",
    "warm-orange": "#ff4d21",
    "warm-violet": "#9e1fd0",
    "mint-raw": "#4fe6c3",
    "blue-raw": "#2e9bff",
    "violet-raw": "#b57fe0",
  }),
  dark: Object.freeze({
    bg: "#1a1614",
    surface: "#262019",
    "surface-inset": "#201b17",
    border: "#37302a",
    "text-primary": "#f8f4ed",
    "text-secondary": "#c4bdb2",
    "text-muted": "#8a847c",
    "on-primary": "#f8f4ed",
  }),
  radius: Object.freeze({
    sm: "12px",
    md: "18px",
    lg: "24px",
    xl: "30px",
    pill: "999px",
  }),
  font: Object.freeze({
    display: "Space Grotesk",
    body: "Inter",
  }),
});
